- name: docker_housekeeper - copy docker-housekeeper systemd service
  copy:
    src: docker-housekeeper/docker-housekeeper.service
    dest: /etc/systemd/system/docker-housekeeper.service
  notify:
    - reload systemd

- name: docker_housekeeper - copy docker-housekeeper systemd timer
  copy:
    src: docker-housekeeper/docker-housekeeper.timer
    dest: /etc/systemd/system/docker-housekeeper.timer
  notify:
    - reload systemd

- name: docker_housekeeper - disable docker-housekeeper systemd service
  systemd:
    name: docker-housekeeper.service
    enabled: no
    daemon_reload: yes

- name: docker_housekeeper - enable docker-housekeeper systemd timer
  systemd:
    name: docker-housekeeper.timer
    enabled: yes
    daemon_reload: yes
