- name: install - Docker dependencies
  apt:
    name:
      - python3
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present

- name: install - Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: '{{ "present" if docker_install_from_official_repo else "absent" }}'

- name: install - Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: '{{ "present" if docker_install_from_official_repo else "absent" }}'

- block:
    - name: install - remove docker.io
      apt:
        name: docker.io
        state: absent
    - name: install - install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: true
  when: docker_install_from_official_repo

- block:
    - name: install - remove docker-ce
      apt:
        name: docker-ce
        state: absent
    - name: install - install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: true
  when: not docker_install_from_official_repo

- name: install - install Docker Python3 library
  pip:
    name:
      - docker
    executable: pip3

- name: install - copy daemon.json
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
