- name: make apt stop installing useless shit (Debian)
  copy:
    dest: /etc/apt/apt.conf.d/999norecommend
    content: |
      APT::Install-Recommends "0";
      APT::Install-Suggests "0";
  when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint", "OSMC"]

- name: remove Canonical malware (Ubuntu)
  apt:
    name:
      - lxc
      - lxd
      - lxd-agent-loader
      - lxd-installer
      - motd-news-config
      - snapd
      - ubuntu-pro-client
      - ubuntu-release-upgrader-core
      - unattended-upgrades
      - update-notifier-common
    state: absent
    autoremove: true
    clean: true
    purge: true
  when: ansible_distribution in ["Ubuntu", "Linux Mint"]

- name: make apt stop installing snap (Ubuntu)
  copy:
    dest: /etc/apt/preferences.d/nosnap.pref
    content: |
      Package: snapd
      Pin: release a=*
      Pin-Priority: -10
  when: ansible_distribution in ["Ubuntu", "Linux Mint"]

- name: disable motd advertisements
  file:
    path: /etc/update-motd.d/10-help-text
    state: absent

- name: check for motd-news
  stat:
    path: /etc/default/motd-news
  register: motd_news

- when: motd_news.stat.exists
  block:
    - name: disable motd-news
      lineinfile:
        path: /etc/default/motd-news
        line: ENABLED=0
        regexp: ^ENABLED
    - name: clear motd-news urls just in case
      lineinfile:
        path: /etc/default/motd-news
        line: URLS=""
        regexp: ^URLS=
