global:
  scrape_interval: 60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - prometheus.direct.sapslaj.cloud:9093

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - eris.sapslaj.xyz:9090
          - prometheus.direct.sapslaj.cloud:9090
  - job_name: blackbox
    static_configs:
      - targets:
          - eris.sapslaj.xyz:9115
  # - job_name: octoprint
  #   metrics_path: /plugin/prometheus_exporter/metrics
  #   params:
  #     apikey:
  #       - 2D9A4A7692EF498B81A28C055740D573
  #   static_configs:
  #     - targets:
  #         - octopi.sapslaj.xyz:80
  - job_name: node_exporter
    static_configs:
      - targets:
          - eris.sapslaj.xyz:9100
          - mems.sapslaj.xyz:9100
          - playboy.sapslaj.xyz:9100
          # - octopi.sapslaj.xyz:9100
  - job_name: du_spank_bank
    static_configs:
      - targets:
          - mems.sapslaj.xyz:9477
  - job_name: blackbox_http2xx
    metrics_path: /probe
    params:
      module:
        - http_2xx
    relabel_configs: &blackbox_relabel_configs
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
    static_configs:
      - targets:
          - http://eris.sapslaj.xyz:80      # Pi-hole UI
          - http://mems.sapslaj.xyz:7878    # Radarr
          - http://mems.sapslaj.xyz:8080    # Transmission (nginx)
          - http://mems.sapslaj.xyz:8096    # Emby
          - http://mems.sapslaj.xyz:8989    # Sonarr
          - http://mems.sapslaj.xyz:9117    # Jackett
          # - http://octopi.sapslaj.xyz:80    # OctoPrint UI
          - http://playboy.sapslaj.xyz:631  # CUPS UI
  - job_name: blackbox_tcp_connect
    metrics_path: /probe
    params:
      module:
        - tcp_connect
    relabel_configs: *blackbox_relabel_configs
    static_configs:
      - targets:
          - mems.sapslaj.xyz:32400  # Plex
          - eris.sapslaj.xyz:53     # PiHole
          - playboy.sapslaj.xyz:80  # Kodi UI
  - job_name: blackbox_icmp
    metrics_path: /probe
    params:
      module:
        - icmp
    relabel_configs: *blackbox_relabel_configs
    static_configs:
      - targets:
          - mems.sapslaj.xyz
          - eris.sapslaj.xyz
          - playboy.sapslaj.xyz
          # - octopi.sapslaj.xyz
