global:
  scrape_interval: 60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - prometheus.direct.sapslaj.cloud:9093

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: octoprint
    metrics_path: /plugin/prometheus_exporter/metrics
    params:
      apikey:
        - 2D9A4A7692EF498B81A28C055740D573
    static_configs:
      - targets:
          - octopi.homelab.sapslaj.com:80 
  - job_name: node_exporter
    static_configs:
      - targets:
          - eris.homelab.sapslaj.com:9100
          - mems.homelab.sapslaj.com:9100
