- hosts: all
  become: true
  tasks:
    - name: install packages
      apt:
        force_apt_get: true
        name:
          - acl
          - nodejs
          - pipx
          - python-is-python3
          - python3-pip
          - python3-venv
          - unzip

- hosts: all
  become: true
  tasks:
    - name: Install pipx ansible
      community.general.pipx:
        name: ansible
        install_deps: yes
      environment:
        PIPX_HOME: /usr/local/share/pipx
        PIPX_BIN_DIR: /usr/local/bin

- hosts: all
  become: true
  vars_files:
    - secret_vars/all.yml
  roles:
    - role: sapslaj.cloudflare_ddns_update
    - role: sapslaj.playboy_backup
    - role: sapslaj.photography_rebuild

# - hosts: all
#   become: true
#   vars:
#     runner_user: ci
#     github_account: sapslaj
#     github_repo: homelab-pets
#   roles:
#     - role: monolithprojects.github_actions_runner
