- hosts: all
  become: true
  tasks:
    - name: install packages
      apt:
        force_apt_get: true
        name:
          - acl
          - python3-pip
          - python3-venv
    - name: install pipx
      pip:
        name: pipx

- hosts: all
  become: true
  become_user: ci
  tasks:
    - name: Install pipx ansible
      community.general.pipx:
        name: ansible
        install_deps: yes

- hosts: all
  become: true
  vars_files:
    - secret_vars/all.yml
  roles:
    - role: sapslaj.cloudflare_ddns_update
    - role: sapslaj.vsdd

# - hosts: all
#   become: true
#   vars:
#     runner_user: ci
#     github_account: sapslaj
#     github_repo: homelab-pets
#   roles:
#     - role: monolithprojects.github_actions_runner
