version: '2'

services:
  watchtower:
    image: containrrr/watchtower
    restart: 'always'
    container_name: watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

