network_syslog_promtail_volumes_dir: /var/docker/volumes
network_syslog_promtail_push_url: http://loki:3100/loki/api/v1/push
network_syslog_promtail_debug: false
network_syslog_promtail_tcp_port: 6601
network_syslog_promtail_udp_port: 5514
network_syslog_promtail_labels:
  job: network-syslog
network_syslog_promtail_relabel_configs:
  - source_labels: [__syslog_message_hostname]
    target_label: hostname
