name: Deploy docker-compose
description: Copy directory then spin up a docker-compose app
inputs:
  host:
    description: host to run app on
    required: true
  dir:
    description: Full path to app directory
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        basedir="$(basename ${{ inputs.dir }})"
        rsync -rvhP ${{ inputs.dir }} ci@${{ inputs.host }}:
        ssh -t ci@${{ inputs.host }} "cd $basedir ; docker-compose up -d"
