- hosts: all
  become: true
  roles:
    - role: cloudalchemy.coredns
      vars:
        coredns_version: 1.11.1
        coredns_config_file: coredns/Corefile
        coredns_dns_port: 5530
        coredns_key_files_paths: []
        coredns_zone_files_paths: []

- hosts: all
  become: true
  tasks:
    - name: add vsdd user
      user:
        name: vsdd
        password: $6$HZ.QSIxXeW1iKA8N$G3dXZDM/n8qSn2YjiLkW2/0jsVNfcOvDkf5L6agLnWDYSxklDxOIPfrjVT7Lj0XzuYxg.aTt241FdfAaFCQxl.
        append: yes
        groups:
          - coredns
      ignore_errors: "{{ ansible_check_mode }}"
    - name: check for zone file
      stat:
        path: /etc/coredns/sapslaj.xyz.zone
      register: zonefile_stat
    - name: create zone file
      file:
        state: touch
        path: /etc/coredns/sapslaj.xyz.zone
      when: not zonefile_stat.stat.exists
    - name: setup zone file attributes
      file:
        state: file
        path: /etc/coredns/sapslaj.xyz.zone
        owner: vsdd
        group: coredns
    - name: set $ORIGIN
      lineinfile:
        path: /etc/coredns/sapslaj.xyz.zone
        line: $ORIGIN sapslaj.xyz.
        regexp: ^\\$ORIGIN
        insertbefore: BOF
    - name: set $TTL
      lineinfile:
        path: /etc/coredns/sapslaj.xyz.zone
        line: $TTL 300
        regexp: ^\\$TTL
        insertbefore: BOF
    - name: check for SOA record
      shell: test -f /etc/coredns/sapslaj.xyz.zone && grep -q 'sapslaj.xyz. IN SOA' /etc/coredns/sapslaj.xyz.zone
      register: soa_check
      changed_when: false
    - name: add SOA
      lineinfile:
        path: /etc/coredns/sapslaj.xyz.zone
        line: sapslaj.xyz. IN SOA ns-1060.awsdns-04.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 8640
        insertafter: $TTL 300
      when: soa_check.rc != 0
    - name: set SOA
      lineinfile:
        backrefs: true
        path: /etc/coredns/sapslaj.xyz.zone
        line: sapslaj.xyz. IN SOA ns-1060.awsdns-04.org. awsdns-hostmaster.amazon.com. \1 7200 900 1209600 8640
        regexp: ^sapslaj.xyz. IN SOA ns-1060.awsdns-04.org. awsdns-hostmaster.amazon.com. (\d+) 7200 900 1209600 8640
        insertafter: $TTL 300
      when: soa_check.rc == 0
    - name: set NS records
      lineinfile:
        path: /etc/coredns/sapslaj.xyz.zone
        line: sapslaj.xyz. IN 172800 NS {{ item }}
        insertafter: ^sapslaj.xyz. IN SOA
      loop:
        - ns-1060.awsdns-04.org.
        - ns-1955.awsdns-52.co.uk.
        - ns-335.awsdns-41.com.
        - ns-605.awsdns-11.net.
