- hosts: all
  become: true
  roles:
    - role: cloudalchemy.coredns
      vars:
        coredns_version: 1.11.1
        coredns_config_file: coredns/Corefile
        coredns_dns_port: 5530
        coredns_key_files_paths: []
        coredns_zone_files_paths: []

- hosts: all
  become: true
  tasks:
    - name: copy zone
      copy:
        src: coredns/sapslaj.xyz.zone
        dest: /etc/coredns/sapslaj.xyz.zone
    - name: add vsdd user
      user:
        name: vsdd
        password: $6$HZ.QSIxXeW1iKA8N$G3dXZDM/n8qSn2YjiLkW2/0jsVNfcOvDkf5L6agLnWDYSxklDxOIPfrjVT7Lj0XzuYxg.aTt241FdfAaFCQxl.
        append: yes
        groups:
          - coredns
      ignore_errors: "{{ ansible_check_mode }}"
