- hosts: all
  become: true
  handlers:
    - name: restart NetworkManager
      systemd:
        name: NetworkManager.service
        state: restarted
    - name: restart libvirtd
      systemd:
        name: libvirtd.service
        state: restarted
  tasks:
    - import_tasks: tasks/storage.yml
    - import_tasks: tasks/networking.yml
    - import_tasks: tasks/libvirt.yml
    - import_tasks: tasks/cockpit.yml
