- hosts: all
  become: true
  handlers:
    - name: restart NetworkManager
      systemd:
        name: NetworkManager.service
        state: restarted
    - name: restart libvirtd
      systemd:
        name: libvirtd.service
        state: restarted
    - name: restart nfs-kernel-server
      systemd:
        name: nfs-kernel-server.service
        state: restarted
    - name: restart du_exporter service
      systemd:
        name: du_exporter.service
        state: restarted
        daemon_reload: yes
    - name: restart libvirt_exporter service
      systemd:
        name: libvirt_exporter.service
        state: restarted
        daemon_reload: yes
  tasks:
    - import_tasks: tasks/storage.yml
    - import_tasks: tasks/networking.yml
    - import_tasks: tasks/libvirt.yml
    - import_tasks: tasks/nfs.yml
    - import_tasks: tasks/cockpit.yml
