- name: setup Vector repo
  command:
    cmd: /bin/bash -c 'eval "$(curl -L https://setup.vector.dev)"'
    creates: /etc/apt/sources.list.d/vector.list
  notify:
    - restart vector.service

- name: install Vector
  apt:
    name: vector
    state: present
    update_cache: true
  notify:
    - restart vector.service

- name: configure envvars
  template:
    src: vector.env.j2
    dest: /etc/default/vector
  notify:
    - restart vector.service

- name: configure vector
  template:
    src: vector.yaml.j2
    dest: /etc/vector/vector.yaml

- meta: flush_handlers

- name: start and enable vector
  systemd:
    name: vector.service
    state: started
    enabled: true
