- hosts: all
  become: true
  tasks:
    - name: install NFS packages
      apt:
        name:
          - nfs-common
    - name: mount exos
      mount:
        src: 172.24.4.10:/mnt/exos
        path: /mnt/exos
        fstype: nfs4
        state: mounted

- hosts: all
  become: true
  roles:
    - role: sapslaj.docker_standalone
