- hosts: all
  become: true
  tasks:
    - name: disable AppArmor # Yes. I know. Don't @ me
      systemd:
        name: apparmor.service
        enabled: no
        state: stopped

- hosts: all
  become: true
  roles: []
