- hosts: all
  become: true
  tasks:
    - name: disable AppArmor # Yes. I know. Don't @ me
      systemd:
        name: apparmor.service
        enabled: no
        state: stopped

- hosts: all
  become: true
  roles:
    - role: sapslaj.syncthing
    - role: sapslaj.morbius
    - role: sapslaj.plex
      vars:
        plex_media_dir: /mnt/exos/Media
    - role: sapslaj.jellyfin
      vars:
        jellyfin_media_dir: /mnt/exos/Media
    - role: sapslaj.syslog_promtail
      vars:
        syslog_promtail_volumes_dir: /var/docker/volumes/syslog-promtail
