promtail_loki_server_url: http://loki.sapslaj.xyz
promtail_extra_parameters: --client.external-labels=hostname=%H
promtail_config_scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        target_label: systemd_unit
      - source_labels: [__journal__hostname]
        target_label: systemd_hostname
      - source_labels: [__journal_syslog_identifier]
        target_label: systemd_syslog_identifier
  - job_name: syslog
    syslog:
      listen_address: 127.0.0.1:5144
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: syslog
    relabel_configs:
      - source_labels: [__syslog_message_severity]
        target_label: syslog_severity
      - source_labels: [__syslog_message_facility]
        target_label: syslog_facility
      - source_labels: [__syslog_message_hostname]
        target_label: syslog_hostname
      - source_labels: [__syslog_message_app_name]
        target_label: syslog_app_name
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_name]
        target_label: container
