version: '2'
services:
  app:
    image: linuxserver/plex
    restart: 'always'
    container_name: plex
    entrypoint: []
    command: /bin/bash -c '/init'
    environment:
      VERSION: latest
      TZ: America/New_York
    network_mode: host
    volumes:
      - /mnt/spank-bank/Media:/data/media:ro
      - plex-config:/config
volumes:
  plex-config:
