- hosts: all
  become: true
  tasks:
    - name: config directory
      file:
        path: /mnt/spank-bank/volumes/plex/plex-config
        state: directory
    - name: plex container
      docker_container:
        name: plex
        image: linuxserver/plex
        restart_policy: unless-stopped
        network_mode: host
        env:
          TZ: America/New_York
        volumes:
          - /mnt/spank-bank/volumes/plex/plex-config:/config
          - /mnt/spank-bank/Media:/data/media:ro
    - name: allow port 32400 in firewalld
      firewalld:
        port: 32400/tcp
        permanent: yes
        immediate: yes
        state: enabled
