---
- set_fact:
    _common_system_user: "{{ node_exporter_system_user }}"
    _common_system_group: "{{ node_exporter_system_group }}"
    _common_config_dir: "{{ node_exporter_config_dir }}"
    _common_tls_server_config: "{{ node_exporter_tls_server_config }}"
    _common_http_server_config: "{{ node_exporter_http_server_config }}"
    _common_basic_auth_users: "{{ node_exporter_basic_auth_users }}"
    _common_service_name: node_exporter

- name: "Create systemd service unit {{ _common_service_name }}"
  ansible.builtin.template:
    src: "{{ _common_service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ _common_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - "Restart {{ _common_service_name }}"

- name: "Create config dir {{ _common_config_dir }}"
  ansible.builtin.file:
    path: "{{ _common_config_dir }}"
    state: directory
    owner: "{{ _common_system_user }}"
    group: "{{ _common_system_group }}"
    mode: u+rwX,g+rwX,o=rX
  become: true
  notify:
    - "Restart {{ _common_service_name }}"
  when: _common_config_dir is defined

- name: "Install web config for {{ _common_service_name }}"
  ansible.builtin.template:
    src: "web_config.yml.j2"
    dest: "{{ _common_config_dir }}/web_config.yml"
    owner: "{{ _common_system_user }}"
    group: "{{ _common_system_group }}"
    mode: 0644
  become: true
  notify:
    - "Restart {{ _common_service_name }}"
  when: "[_common_tls_server_config, _common_http_server_config, _common_basic_auth_users] | map('length') | select('>', 0) | list is any"

- name: Create textfile collector dir
  ansible.builtin.file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: u+rwX,g+rwX,o=rX
  become: true
  when: node_exporter_textfile_dir | length > 0
  tags:
    - node_exporter
    - configure
    - node_exporter_configure
