---
- set_fact:
    _common_web_listen_address: "{{ node_exporter_web_listen_address }}"

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_facts['service_mgr'] == 'systemd'
    msg: "This module only works with systemd"

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _common_dependencies }}"
    state: present
  when: _common_dependencies is defined

- name: Gather package facts
  ansible.builtin.package_facts:
  when: "not 'packages' in ansible_facts"

- name: Naive assertion of proper listen address
  ansible.builtin.assert:
    that:
      - >-
        [_common_web_listen_address] |
          flatten |
          reject('match', '.+:\\d+$') |
          list |
          length == 0
  when: _common_web_listen_address is defined

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        node_exporter_web_listen_address is string
        or
        (
          node_exporter_version is version('1.5.0', '>=') and
          node_exporter_web_listen_address | type_debug == "list"
        )

- name: Assert collectors are not both disabled and enabled at the same time
  ansible.builtin.assert:
    that:
      - "item not in node_exporter_enabled_collectors"
  with_items: "{{ node_exporter_disabled_collectors }}"

- name: Assert that TLS config is correct
  when: node_exporter_tls_server_config | length > 0
  block:
    - name: Assert that TLS key and cert path are set
      ansible.builtin.assert:
        that:
          - "node_exporter_tls_server_config.cert_file is defined"
          - "node_exporter_tls_server_config.key_file is defined"

    - name: Check existence of TLS cert file
      ansible.builtin.stat:
        path: "{{ node_exporter_tls_server_config.cert_file }}"
      register: __node_exporter_cert_file

    - name: Check existence of TLS key file
      ansible.builtin.stat:
        path: "{{ node_exporter_tls_server_config.key_file }}"
      register: __node_exporter_key_file

    - name: Assert that TLS key and cert are present
      ansible.builtin.assert:
        that:
          - "__node_exporter_cert_file.stat.exists"
          - "__node_exporter_key_file.stat.exists"

- name: Discover latest version
  ansible.builtin.set_fact:
    node_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _node_exporter_repo }}/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: node_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - node_exporter_version == "latest"
  tags:
    - node_exporter
    - install
    - node_exporter_install
    - download
    - node_exporter_download
