apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: signoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      volumes:
        - name: data-volumeclaim-template-chi-signoz-clickhouse-cluster-0-0-0
          persistentVolumeClaim:
            claimName: data-volumeclaim-template-chi-signoz-clickhouse-cluster-0-0-0
      containers:
        - name: ubuntu
          image: ubuntu:24.04
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - mountPath: /data-volumeclaim-template-chi-signoz-clickhouse-cluster-0-0-0
              name: data-volumeclaim-template-chi-signoz-clickhouse-cluster-0-0-0
