- name: create /tmp/seaweedfs-3.86
  file:
    path: /tmp/seaweedfs-3.86
    state: directory

- name: download and unarchive SeaweedFS tarball
  unarchive:
    src: https://github.com/seaweedfs/seaweedfs/releases/download/3.86/linux_amd64.tar.gz
    dest: /tmp/seaweedfs-3.86
    remote_src: true
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - restart weed.service

- name: copy weed binary to /usr/local/bin
  copy:
    src: /tmp/seaweedfs-3.86/weed
    dest: /usr/local/bin/weed
    remote_src: true
    mode: a+x
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - restart weed.service

- name: copy weed.service
  copy:
    src: weed.service
    dest: /etc/systemd/system/weed.service
  notify:
    - restart weed.service

- meta: flush_handlers

- name: enable weed.service
  systemd:
    name: weed.service
    state: started
    enabled: true
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
