- name: config directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ network_syslog_vector_volumes_dir }}/syslog-ng-config"
    - "{{ network_syslog_vector_volumes_dir }}/vector-config"
    - "{{ network_syslog_vector_volumes_dir }}/vector-data"

- name: syslog-ng config
  template:
    src: syslog-ng.conf.j2
    dest: "{{ network_syslog_vector_volumes_dir }}/syslog-ng-config/syslog-ng.conf"
  register: syslog_ng_config

- name: syslog-ng container
  docker_container:
    name: syslog-ng
    image: lscr.io/linuxserver/syslog-ng
    restart_policy: unless-stopped
    restart: "{{ syslog_ng_config.changed }}"
    network_mode: host
    env:
      TZ: Etc/UTC
    command:
      - tail
      - -f
      - /config/log/current
      - /config/log/debug.log
    volumes:
      - "{{ network_syslog_vector_volumes_dir }}/syslog-ng-config:/config"

- name: vector config
  template:
    src: vector.yaml.j2
    dest: "{{ network_syslog_vector_volumes_dir }}/vector-config/vector.yaml"
  register: vector_config

- name: vector container
  docker_container:
    name: vector
    image: proxy.oci.sapslaj.xyz/docker-hub/timberio/vector:0.48.0-debian
    restart_policy: unless-stopped
    restart: "{{ vector_config.changed }}"
    ports:
      - 127.0.0.1:1514:1514
    volumes:
      - "{{ network_syslog_vector_volumes_dir }}/vector-config:/etc/vector"
      - "{{ network_syslog_vector_volumes_dir }}/vector-data:/var/lib/vector"
