- name: config directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ syslog_promtail_volumes_dir }}/syslog-ng-config'
    - '{{ syslog_promtail_volumes_dir }}/promtail-config'
- name: syslog-ng config
  copy:
    src: syslog-ng.conf
    dest: '{{ syslog_promtail_volumes_dir }}/syslog-ng-config/syslog-ng.conf'
  register: syslog_ng_config
- name: syslog-ng container
  docker_container:
    name: syslog-ng
    image: lscr.io/linuxserver/syslog-ng
    restart_policy: unless-stopped
    restart: '{{ syslog_ng_config.changed }}'
    network_mode: host
    env:
      TZ: America/New_York
    command:
      - tail
      - -f
      - /config/log/current
      - /config/log/debug.log
    volumes:
      - '{{ syslog_promtail_volumes_dir }}/syslog-ng-config:/config'
- name: promtail config
  copy:
    src: promtail.yaml
    dest: '{{ syslog_promtail_volumes_dir }}/promtail-config/promtail.yaml'
  register: promtail_config
- name: promtail container
  docker_container:
    name: promtail
    image: grafana/promtail
    restart_policy: unless-stopped
    restart: '{{ promtail_config.changed }}'
    ports:
      - 127.0.0.1:1514:1514
    command:
      - -config.file=/etc/promtail/promtail.yaml
    volumes:
      - '{{ syslog_promtail_volumes_dir }}/promtail-config:/etc/promtail'
