- hosts: all
  become: true
  roles:
    - role: sapslaj.ansible_target
    - role: sapslaj.users
    - role: sapslaj.selfheal
    - role: sapslaj.waifu_motd
    - role: cloudalchemy.node_exporter
      when: inventory_hostname not in ["zerotwo.sapslaj.xyz"]
