- hosts: all
  become: true
  roles:
    - role: sapslaj.ansible_target
    - role: sapslaj.users
    - role: sapslaj.selfheal
    - role: cloudalchemy.node_exporter
      when: inventory_hostname not in ["zerotwo.homelab.sapslaj.com"]
