- hosts: all
  become: true
  roles:
    - role: sapslaj.ansible_target
    - role: sapslaj.unfuck_ubuntu
    - role: sapslaj.users

- hosts: all
  become: true
  roles:
    - role: sapslaj.vector
      vars:
        vector_enable_dns: "{{ 'dns_servers' in group_names }}"

- hosts: all
  become: true
  roles:
    - role: sapslaj.selfheal
    - role: sapslaj.waifu_motd
    - role: sapslaj.rsyslog_vector

- hosts: nas_clients
  become: true
  roles:
    - role: sapslaj.nas_client

- hosts: bare_hosts
  become: true
  roles:
    - role: prometheus.prometheus.node_exporter
    # - role: cloudalchemy.process_exporter
    #   vars:
    #     process_exporter_version: 0.7.10

- hosts: qemu_guests
  become: true
  roles:
    - role: sapslaj.qemu_guest
