- hosts: all
  become: true
  roles:
    - role: sapslaj.ansible_target
    - role: sapslaj.users
    - role: sapslaj.selfheal
    - role: sapslaj.waifu_motd

- hosts: all
  become: true
  roles:
    - role: patrickjahns.promtail
    - role: sapslaj.rsyslog_promtail

- hosts: bare_hosts
  become: true
  roles:
    - role: cloudalchemy.node_exporter
    - role: cloudalchemy.process_exporter
      vars:
        process_exporter_version: latest

- hosts: qemu_guests
  become: true
  roles:
    - role: sapslaj.qemu_guest

- hosts: k3s
  become: true
  roles:
    - role: sapslaj.rsync_backup
      vars:
        rsync_backup_timer:
          on_calendar: hourly
        rsync_backup_jobs:
          - src: /var/lib/rancher/k3s
            dest: /mnt/exos/volumes/{{ ansible_hostname }}/k3s-data

- hosts: docker_standalone
  become: true
  roles:
    - role: sapslaj.rsync_backup
      vars:
        rsync_backup_timer:
          on_calendar: hourly
        rsync_backup_jobs:
          - src: /var/docker/volumes
            dest: /mnt/exos/volumes/{{ ansible_hostname }}/docker-volumes
