- hosts: all
  become: true
  roles:
    - role: sapslaj.ansible_target
    - role: sapslaj.users
    - role: patrickjahns.promtail

- hosts: all,!proxmox_hosts
  become: true
  roles:
    - role: sapslaj.selfheal
    - role: sapslaj.waifu_motd
    - role: sapslaj.rsyslog_promtail

- hosts: nas_clients
  become: true
  roles:
    - role: sapslaj.nas_client

- hosts: bare_hosts
  become: true
  roles:
    - role: prometheus.prometheus.node_exporter
    # - role: cloudalchemy.process_exporter
    #   vars:
    #     process_exporter_version: 0.7.10

- hosts: qemu_guests
  become: true
  roles:
    - role: sapslaj.qemu_guest

- hosts: k3s
  become: true
  roles:
    - role: sapslaj.rsync_backup
      vars:
        rsync_backup_timer:
          on_calendar: hourly
          randomized_delay_sec: 1800
          fixed_random_delay: true
        rsync_backup_jobs:
          - src: /var/lib/rancher/k3s/
            dest: /mnt/exos/volumes/{{ ansible_hostname }}/k3s-data/
            additional_parameters: --exclude agent/

- hosts: docker_standalone
  become: true
  roles:
    - role: sapslaj.docker_standalone
    - role: sapslaj.rsync_backup
      vars:
        rsync_backup_timer:
          on_calendar: hourly
          randomized_delay_sec: 1800
          fixed_random_delay: true
        rsync_backup_jobs:
          - src: /var/docker/volumes
            dest: /mnt/exos/volumes/{{ ansible_hostname }}/docker-volumes
