- hosts: all
  become: true
  roles:
    - role: sapslaj.ansible_target
    - role: sapslaj.users
    - role: sapslaj.selfheal
    - role: sapslaj.waifu_motd

- hosts: all
  become: true
  roles:
    - role: cloudalchemy.node_exporter
      when: inventory_hostname not in ["zerotwo.sapslaj.xyz"]
    - role: cloudalchemy.process_exporter
      when: inventory_hostname not in ["zerotwo.sapslaj.xyz"]
      vars:
        process_exporter_version: latest
    - role: patrickjahns.promtail
    - role: sapslaj.rsyslog_promtail

- hosts: qemu_guests
  become: true
  roles:
    - role: sapslaj.qemu_guest
