- name: morbius directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/morbius
    - /var/morbius
    - /var/morbius/mmdb

- name: download MaxMind GeoLite2 MMDBs
  get_url:
    url: "{{ item }}"
    dest: /var/morbius/mmdb/
  with_items:
    - https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb
    - https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb
    - https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb

- name: morbius config
  copy:
    src: morbius-config.yaml
    dest: /etc/morbius/config.yaml
  notify:
    - restart morbius

- name: morbius container
  docker_container:
    name: morbius
    image: ghcr.io/sapslaj/morbius:latest
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - /etc/morbius:/etc/morbius
      - /var/morbius:/var/morbius
