- hosts: all
  become: true
  roles:
    - role: sapslaj.ipv6_shim
      vars:
        ipv6_shim_tcp_ports:
          - port: 80
          - port: 443
          - port: 6601
            state: absent
        ipv6_shim_udp_ports:
          - port: 5514
            state: absent
