- hosts: k3s_master
  become: true
  roles:
    - role: sapslaj.k3s_master
      vars:
        k3s_extra_server_args: --disable traefik

- hosts: k3s_node
  become: true
  roles:
    - role: sapslaj.k3s_node
      vars:
        k3s_master_hostname: zerotwo.sapslaj.xyz
        k3s_token: '{{ hostvars["zerotwo.sapslaj.xyz"]["k3s_token"] }}'

- hosts: all
  become: true
  roles:
    - role: sapslaj.ipv6_shim
      vars:
        ipv6_shim_tcp_ports:
          - port: 80
          - port: 443
          - port: 6601
            state: absent
        ipv6_shim_udp_ports:
          - port: 5514
            state: absent
