- hosts: localhost
  tasks:
    - kubernetes.core.k8s_drain:
        state: cordon
        name: '{{ item | regex_replace("(.+?)\..*", "\1") }}'
      with_items: '{{ groups["all"] }}'

- hosts: k3s_master
  become: true
  serial: 1
  tasks:
    - reboot:

- hosts: k3s_node
  become: true
  serial: 1
  tasks:
    - reboot:

- hosts: localhost
  tasks:
    - kubernetes.core.k8s_drain:
        state: uncordon
        name: '{{ item | regex_replace("(.+?)\..*", "\1") }}'
      with_items: '{{ groups["k3s_node"] }}'

- hosts: localhost
  tasks:
    - wait_for:
        timeout: 300

- hosts: localhost
  tasks:
    - kubernetes.core.k8s_drain:
        state: uncordon
        name: '{{ item | regex_replace("(.+?)\..*", "\1") }}'
      with_items: '{{ groups["k3s_master"] }}'
