- hosts: all
  become: true
  tasks:
    - name: copy exporter
      copy:
        src: du_exporter
        dest: /usr/local/bin/du_exporter
    - name: copy service unit
      copy:
        src: du_exporter.service
        dest: /etc/systemd/system/du_exporter.service
      notify:
        - restart du_exporter service
  handlers:
    - name: restart du_exporter service
      systemd:
        name: du_exporter.service
        state: restarted
        daemon_reload: yes
