- name: install libs
  pip:
    name:
      - boto3
      - netmiko
- name: copy script
  copy:
    src: vsdd.py
    dest: /usr/sbin/vsdd.py
- name: copy service unit
  template:
    src: vsdd.service.j2
    dest: /etc/systemd/system/vsdd.service
  notify:
    - restart vsdd service
- name: copy timer unit
  copy:
    src: vsdd.timer
    dest: /etc/systemd/system/vsdd.timer
  notify:
    - restart vsdd timer
- name: start vsdd timer
  systemd:
    name: vsdd.timer
    state: started
    enabled: true
