name: Run Playbook
description: run an ansible playbook
inputs:
  dir:
    description: Change directory
    default: ./
  playbook:
    description: playbook
    default: main.yml
  inventory:
    description: inventory
    default: inventory
  args:
    description: extra Ansible args
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        ansible --version
        cd "${{ inputs.dir }}"
        ansible-playbook -i "${{ inputs.inventory }}" -u ci "${{ inputs.playbook }}" ${{ inputs.args }}
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
        ANSIBLE_FORCE_COLOR: 'True'
        ANSIBLE_STDOUT_CALLBACK: yaml
