name: Run Playbook
description: run an ansible playbook
inputs:
  dir:
    description: Change directory
    default: ./
  playbook:
    description: playbook
    default: main.yml
  inventory:
    description: inventory
    default: inventory
  args:
    description: extra Ansible args
    default: ''
  vault_password:
    description: Ansible Vault password
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        source ~/.profile
        cd "${{ inputs.dir }}"
        COMPUTED_ARGS=""
        if [[ -n "${{ inputs.vault_password }}" ]]; then
          echo '${{ inputs.vault_password }}' > vault_password
          COMPUTED_ARGS="$COMPUTED_ARGS --vault-password-file=vault_password"
        fi
        set -x
        ls -lah
        ansible --version
        echo $COMPUTED_ARGS
        ansible-playbook -i "${{ inputs.inventory }}" -u ci "${{ inputs.playbook }}" $COMPUTED_ARGS ${{ inputs.args }}
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
        ANSIBLE_FORCE_COLOR: 'True'
        ANSIBLE_STDOUT_CALLBACK: yaml
