- name: restart cloudflare-ddns-update service
  systemd:
    name: cloudflare-ddns-update.service
    state: restarted
    daemon_reload: yes
- name: restart cloudflare-ddns-update timer
  systemd:
    name: cloudflare-ddns-update.timer
    state: restarted
    daemon_reload: yes
