- name: transmission container
  docker_container:
    name: transmission
    image: haugene/transmission-openvpn
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ulimits:
      - nofile:32768:32768
    dns_servers:
      - 1.1.1.1
      - 1.0.0.1
    env:
      OPENVPN_PROVIDER: '{{ transmission_openvpn_provider | trim }}'
      OPENVPN_USERNAME: '{{ transmission_openvpn_username | trim }}'
      OPENVPN_PASSWORD: '{{ transmission_openvpn_password | trim }}'
      NORDVPN_COUNTRY: '{{ transmission_nordvpn_country | trim }}'
      NORDVPN_PROTOCOL: '{{ transmission_nordvpn_protocol | trim }}'
      TRANSMISSION_DOWNLOAD_QUEUE_ENABLED: 'false'
    volumes:
      - '{{ transmission_data_dir }}:/data'

- name: transmission proxy container
  docker_container:
    name: transmission-proxy
    image: haugene/transmission-openvpn-proxy
    restart_policy: unless-stopped
    links:
      - transmission:transmission
    ports:
      - 9091:8080
