version: '2'

services:
  emby:
    image: emby/embyserver:latest
    restart: 'always'
    container_name: emby
    #network_mode: host
    ports:
      - '8096:8096'
      - '8920:8920'
    volumes:
      - emby-data:/config
      - /mnt/spank-bank/Media:/data/media:ro
      
volumes:
  emby-data:
  
