- hosts: all
  become: true
  tasks:
    - name: config directory
      file:
        path: /mnt/spank-bank/volumes/emby/emby-config
        state: directory
    - name: emby container
      docker_container:
        name: emby
        image: emby/embyserver:latest
        restart_policy: unless-stopped
        network_mode: host
        env:
          TZ: America/New_York
        volumes:
          - /mnt/spank-bank/volumes/emby/emby-config:/config
          - /mnt/spank-bank/Media:/mnt/media:ro
    - name: allow port(s) in firewalld
      firewalld:
        port: '{{ item }}'
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - 8096/tcp # HTTP
        - 8920/tcp # HTTPS
