- name: install codesync
  community.general.pipx:
    name: codesync
    source: git+https://github.com/sapslaj/codesync.git
  environment:
    PIPX_HOME: /usr/local/share/pipx
    PIPX_BIN_DIR: /usr/local/bin
- name: copy codesync config
  copy:
    src: codesync.yaml
    dest: /etc/codesync.yaml
  notify:
    - run codesync
- name: copy service unit
  template:
    src: codesync.service.j2
    dest: /etc/systemd/system/codesync.service
- name: copy timer unit
  copy:
    src: codesync.timer
    dest: /etc/systemd/system/codesync.timer
- name: start codesync timer
  systemd:
    daemon_reload: true
    name: codesync.timer
    state: started
    enabled: true
