version: '3'
services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/spank-bank/Media/:/data
    env_file:
      - .env
  transmission-proxy:
    image: haugene/transmission-openvpn-proxy
    container_name: transmission-proxy
    restart: unless-stopped
    links:
      - transmission
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
  # nyaa-proxy:
  #   build: ./nyaa-proxy
  #   network_mode: service:vpn
  #   command: nyaa-proxy --port=8081 --backend=https://nyaa.si
  #   restart: unless-stopped
  # nyaa-proxy-proxy: # vpn container refuses to forward traffic from outside the host to nyaa-proxy for whatever reason.
  #   image: dperson/nginx
  #   ports:
  #     - 8081:80
  #   command: -w "http://vpn:8081/;/"
  #   restart: unless-stopped
