version: '3'
services:
  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - w569ut7zbkiqf5b.xyz:104.28.28.105
      - zwyr157wwiu6eior.com:104.17.188.107
      - boi9osyg1uwtyafn.com:104.16.229.42
  transmission:
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/spank-bank/Media/:/data
    env_file:
      - .env
  transmission-proxy:
    image: haugene/transmission-openvpn-proxy
    restart: unless-stopped
    links:
      - transmission
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: service:vpn
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - radarr-config:/config
      - /mnt/spank-bank/Media/:/data
    restart: unless-stopped
  radarr-proxy:
    image: dperson/nginx
    links:
      - vpn:radarr
    ports:
      - 7878:80
    command: -w "http://radarr:7878/;/"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: service:vpn
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - sonarr-config:/config
      - /mnt/spank-bank/Media/:/data
    restart: unless-stopped
  sonarr-proxy:
    image: dperson/nginx
    links:
      - vpn:sonarr
    ports:
      - 8989:80
    command: -w "http://sonarr:8989/;/"
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: service:vpn
    environment:
      PUID: 0
      PGID: 0
      TZ: America/New_York
    volumes:
      - jackett-config:/config
      #- :/downloads
    restart: unless-stopped
  jackett-proxy:
    image: dperson/nginx
    links:
      - vpn:jackett
    ports:
      - 9117:80
    command: -w "http://jackett:9117/;/"
    restart: unless-stopped

volumes:
  jackett-config:
    driver: local
  radarr-config:
    driver: local
  sonarr-config:
    driver: local
