- hosts: all
  become: true
  vars_files:
    - secret_vars/all.yml
  tasks:
    - name: install libs
      pip:
        name:
          - requests
          - cloudflare
    - name: copy script
      copy:
        src: cloudflare-ddns-update.py
        dest: /usr/sbin/cloudflare-ddns-update.py
    - name: copy service unit
      template:
        src: cloudflare-ddns-update.service
        dest: /etc/systemd/system/cloudflare-ddns-update.service
      notify:
        - restart cloudflare-ddns-update service
    - name: copy timer unit
      copy:
        src: cloudflare-ddns-update.timer
        dest: /etc/systemd/system/cloudflare-ddns-update.timer
      notify:
        - restart cloudflare-ddns-update timer
  handlers:
    - name: restart cloudflare-ddns-update service
      systemd:
        name: cloudflare-ddns-update.service
        state: restarted
        daemon_reload: yes
    - name: restart cloudflare-ddns-update timer
      systemd:
        name: cloudflare-ddns-update.timer
        state: restarted
        daemon_reload: yes
