- name: check is bash shell exists
  stat:
    path: /bin/bash
  register: stat_bash

- name: set passwordless sudo
  lineinfile:
    path: /etc/sudoers
    line: "%admin ALL=(ALL) NOPASSWD:ALL"
    regexp: "^%admin ALL=(ALL)"

- name: add admin group
  group:
    name: admin
    state: present

- name: add users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    append: yes
    groups:
      - admin
  with_items: "{{ common_users }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: add users ssh key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  with_items: "{{ common_users }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: set default shell to bash if permitted
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
  with_items: "{{ common_users }}"
  when: stat_bash.stat.exists and stat_bash.stat.xoth and inventory_hostname not in item.no_manage_shell_hosts|default([])
  ignore_errors: "{{ ansible_check_mode }}"
