- name: copy service unit
  copy:
    src: photography-rebuild.service
    dest: /etc/systemd/system/photography-rebuild.service
  notify:
    - restart photography-rebuild service
- name: copy timer unit
  copy:
    src: photography-rebuild.timer
    dest: /etc/systemd/system/photography-rebuild.timer
  notify:
    - restart photography-rebuild timer
- name: start photography-rebuild timer
  systemd:
    name: photography-rebuild.timer
    state: started
    enabled: true
