name: Aqua / Ansible
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/aqua-ansible.yml
      - aqua/ansible/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: aqua/ansible
          inventory: aqua.sapslaj.xyz,
          vault_password: ${{ secrets.vault_password }}
