name: Common / Ansible
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/common-ansible.yml
      - common/ansible/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: common/ansible
