name: Common / Ansible
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/common-ansible.yml
      - common/ansible/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd common/ansible
          ansible-playbook -i inventory -u ci main.yml
