name: Common / Ansible
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/common-ansible.yml
      - common/ansible/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        run: |
          cd common/ansible
          ansible-playbook -i inventory -u ci main.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
          ANSIBLE_FORCE_COLOR: 'True'
          ANSIBLE_STDOUT_CALLBACK: yaml
