name: Common / Ansible / Update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * 2
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: common/ansible
          playbook: update.yml
