name: Eris / Cloudflare DDNS Updater
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/eris-cloudflare-ddns-update.yml
      - eris/cloudflare-ddns-update/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: eris/cloudflare-ddns-update
          inventory: eris.homelab.sapslaj.com,
          vault_password: ${{ secrets.vault_password }}
