name: Eris / Pi-hole
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/eris-pihole.yml
      - eris/pihole/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: eris/pihole
          inventory: eris.sapslaj.xyz,
