name: ganyu
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ganyu.yml
      - common/pulumi/**
      - ganyu/**

env:
  INFISICAL_API_URL: ${{ secrets.INFISICAL_API_URL }}
  INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
  INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
  NODE_AUTH_TOKEN: ${{ secrets.GH_ACTIONS_READ_TOKEN }}
  PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_ENDPOINT }}
  PROXMOX_VE_INSECURE: 'true'
  PROXMOX_VE_PASSWORD: ${{ secrets.PROXMOX_VE_PASSWORD }}
  PROXMOX_VE_USERNAME: ${{ secrets.PROXMOX_VE_USERNAME }}
  PULUMI_CONFIG_PASSPHRASE: ''
  VYOS_HOST: ${{ secrets.VYOS_HOST }}
  VYOS_PASSWORD: ${{ secrets.VYOS_PASSWORD }}
  VYOS_USERNAME: ${{ secrets.VYOS_USERNAME }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: https://npm.pkg.github.com
      - run: npm ci --ignore-scripts
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: prod
          cloud-url: s3://sapslaj-tf-state?region=us-east-1&awssdk=v2&profile=default
          work-dir: ./ganyu
