name: Koyuki / Ansible
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/koyuki-ansible.yml
      - koyuki/ansible/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: koyuki/ansible
          inventory: koyuki.sapslaj.xyz,
          vault_password: ${{ secrets.vault_password }}
