name: Maki / Ansible
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/maki-ansible.yml
      - maki/ansible/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: maki/ansible
          inventory: maki.sapslaj.xyz,
          vault_password: ${{ secrets.vault_password }}
