name: Mems / PVR
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/mems-pvr.yml
      - mems/pvr/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: mems/pvr
          inventory: mems.sapslaj.xyz,
          vault_password: ${{ secrets.vault_password }}
