name: Playboy / CUPS
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/playboy-cups.yml
      - playboy/cups/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: playboy/cups
          inventory: playboy.homelab.sapslaj.com,
