name: Rem+Ram / Ansible
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/rem-ram-ansible.yml
      - rem-ram/ansible/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-playbook
        uses: ./.github/actions/run-playbook
        with:
          dir: rem-ram/ansible
          inventory: inventory
          vault_password: ${{ secrets.vault_password }}
