- name: install KVM packages
  apt:
    name:
      - netcat
      - ovmf
      - ovmf-ia32
      - qemu-system
      - qemu-utils
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
- name: extra packages for Terraform provider
  apt:
    name:
      - curl
      - git
- name: add users to libvirt group
  user:
    name: '{{ item }}'
    append: yes
    groups:
      - libvirt
  with_items:
    - ci
    - sapslaj
- name: chown libvirt default pool
  file:
    dest: /var/lib/libvirt/images
    recurse: true
    owner: root
    group: libvirt
    mode: g+rwx
- name: disable qemu security driver so libvirt TF provider works
  lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: ^#?security_driver =
    line: security_driver = "none"
  notify:
    - restart libvirtd
- name: copy libvirt_exporter
  copy:
    src: libvirt/libvirt_exporter
    dest: /usr/local/bin/libvirt_exporter
    mode: a+x
  notify:
    - restart libvirt_exporter service
- name: copy libvirt_exporter service
  copy:
    src: libvirt/libvirt_exporter.service
    dest: /etc/systemd/system/libvirt_exporter.service
  notify:
    - restart libvirt_exporter service
- meta: flush_handlers
- name: enable libvirt_exporter service
  systemd:
    name: libvirt_exporter.service
    state: started
    enabled: true
    daemon_reload: yes
