- name: Set net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
- name: Set net.ipv6.conf.all.forwarding=1
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
- name: Set net.ipv6.conf.default.forwarding=1
  sysctl:
    name: net.ipv6.conf.default.forwarding
    value: '1'
    sysctl_set: yes

- name: install networking packages
  apt:
    name:
      - lldpd
      - network-manager
- name: set NetworkManager to manage all interfaces
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: ^managed=
    line: managed=true
  notify:
    - restart NetworkManager
- meta: flush_handlers

- name: set enp10s0
  nmcli:
    state: present
    conn_name: enp10s0
    method4: auto
    method6: auto

- name: set enp7s0f0
  nmcli:
    state: present
    conn_name: enp7s0f0
    dns4:
      - 172.24.4.2
      - 172.24.4.3
    dns4_search:
      - sapslaj.xyz
    dns6:
      - 2001:470:e022:4::2
      - 2001:470:e022:4::3
    dns6_search:
      - sapslaj.xyz
    gw4: 172.24.4.1
    gw6: 2001:470:e022:4::1
    ifname: enp7s0f0
    ip4:
      - 172.24.4.10/24
    ip6:
      - 2001:470:e022:4::a/64
    method4: manual
    method6: manual
    type: ethernet

- name: set enp5s0f0.4
  nmcli:
    state: absent
    conn_name: enp5s0f0.4
    type: vlan
    vlandev: enp5s0f0
    vlanid: 4
    method4: manual
    method6: manual
    ip4: 172.24.4.10/24
    ip6: 2001:470:e022:4::a/64

- name: set enp7s0f2
  nmcli:
    state: present
    conn_name: enp7s0f2
    type: ethernet
    method4: disabled
    method6: disabled

- name: set vm.br0.4
  nmcli:
    state: present
    conn_name: vm.br0.4
    type: bridge
    method4: disabled
    method6: disabled
    priority: 36864
- name: set enp7s0f2.4
  nmcli:
    state: present
    conn_name: enp7s0f2.4
    master: vm.br0.4
    type: vlan
    vlandev: enp7s0f2
    vlanid: 4
    slave_type: bridge
- name: set enp5s0f1.4
  nmcli:
    state: absent
    conn_name: enp5s0f1.4
    master: vm.br0.4
    type: vlan
    vlanid: 4

- name: set vm.br0.5
  nmcli:
    state: present
    conn_name: vm.br0.5
    type: bridge
    method4: disabled
    method6: disabled
    priority: 36864
- name: set enp7s0f2.5
  nmcli:
    state: present
    conn_name: enp7s0f2.5
    master: vm.br0.5
    type: vlan
    vlandev: enp7s0f2
    vlanid: 5
    slave_type: bridge
- name: set enp5s0f1.5
  nmcli:
    state: absent
    conn_name: enp5s0f1.5
    master: vm.br0.5
    type: vlan
    vlanid: 5
