- name: Set net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
- name: Set net.ipv6.conf.all.forwarding=1
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
- name: Set net.ipv6.conf.default.forwarding=1
  sysctl:
    name: net.ipv6.conf.default.forwarding
    value: '1'
    sysctl_set: yes

- name: install NetworkManager
  apt:
    name: network-manager
- name: set NetworkManager to manage all interfaces
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: ^managed=
    line: managed=true
  notify:
    - restart NetworkManager
- meta: flush_handlers

- name: setup bond
  nmcli:
    state: present
    type: bond
    mode: 802.3ad
    conn_name: bond0
- name: add interface to bond
  nmcli:
    state: present
    type: bond-slave
    conn_name: '{{ item }}'
    master: bond0
  with_items:
    - enp5s0f0
    - enp5s0f1
# This ansible task is borked for some reason so I did it manually.
# - name: bond VLAN 4
#   nmcli:
#     state: present
#     type: vlan
#     conn_name: bond0.4
#     vlandev: bond0
#     vlanid: 4

- name: setup bridge
  nmcli:
    state: present
    type: bridge
    conn_name: bridge0
    never_default4: true
    ip4: 172.24.4.10/24
    ip6: 2001:470:e022:4::a/64
- name: add interface to bridge
  nmcli:
    state: present
    type: bridge-slave
    conn_name: '{{ item }}'
    master: bridge0
    hairpin: false
  with_items:
    - bond0.4
