- name: install storage packages
  apt:
    name:
      - mdadm
      - parted
      - udisks2
      - lvm2
      - udisks2-lvm2
      - xfsprogs
      - xfsdump
      - acl
      - attr
      - quota
      - software-properties-common
      - smartmontools
- name: copy du_exporter
  copy:
    src: storage/du_exporter
    dest: /usr/local/bin/du_exporter
    mode: a+x
  notify:
    - restart du_exporter service
- name: copy du_exporter service
  copy:
    src: storage/du_exporter.service
    dest: /etc/systemd/system/du_exporter.service
  notify:
    - restart du_exporter service
- meta: flush_handlers
- name: enable du_exporter service
  systemd:
    name: du_exporter.service
    state: started
    enabled: true
    daemon_reload: yes
